USE DW_DIXIE

sp_columns 

-- TABELA TEMPORARIA PARA DADOS DE CONTAS A PAGAR
DROP TABLE dbo.TMP_BAAN_FAAP003;
CREATE TABLE dbo.TMP_BAAN_FAAP003 (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_CIA				INT,
	NUM_DOCTO			INT,
	COD_ERRO			VARCHAR(10),
	DES_ERRO			VARCHAR(150)
	);

TRUNCATE TABLE dbo.TMP_BAAN_FAAP003
SELECT * FROM dbo.TMP_BAAN_FAAP003


-- TABELA TEMPORARIA PARA DADOS DE CONTAS A RECEBER
DROP TABLE dbo.TMP_BAAN_FAAR003;
CREATE TABLE dbo.TMP_BAAN_FAAR003 (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_CIA				INT,
	NUM_DOCTO			INT,
	COD_ERRO			VARCHAR(10),
	DES_ERRO			VARCHAR(150)
	);



-- Receber os dados da interface SAP_OTC_CAD_FAT.txt
DROP TABLE dbo.TXT_P2P_MOV_ESTOQUE_MENSAL;
CREATE TABLE dbo.TXT_P2P_MOV_ESTOQUE_MENSAL (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(250),	--Plant
	COD_CLASSIF			VARCHAR(250),	--Material Type
	DTA_CORTE			VARCHAR(250),	--Process Date
	COD_ALMOXARIFADO	VARCHAR(250),	--Storage Location
	COD_MATERIAL		VARCHAR(250),	--Material Code	
	COD_PARCEIRO		VARCHAR(250),	--Customer/Vendor
	DTA_ENTRADA_LOTE	VARCHAR(250),	--Entry Date of Batch
	COD_LOTE			VARCHAR(250),	--Batch
	VLR_CUSTO_ESTOQUE	VARCHAR(250),	--Stock Value
	QTD_ESTOQUE			VARCHAR(250),	--Stock Quantity
	QTD_QUILO			VARCHAR(250),	--Total Weight
	QTD_VENDA			VARCHAR(250),	--Sale Quantity
	VLR_VENDA			VARCHAR(250),	--Sale Value
	UND_ESTOQUE			VARCHAR(250)	--Stock Unit
	);

DROP TABLE dbo.STG_P2P_MOV_ESTOQUE_MENSAL;
CREATE TABLE dbo.STG_P2P_MOV_ESTOQUE_MENSAL (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(05),	--Plant
	COD_CLASSIF			VARCHAR(02),	--Material Type
	DTA_CORTE			DATE,			--Process Date
	COD_ALMOXARIFADO	VARCHAR(05),	--Storage Location
	COD_MATERIAL		VARCHAR(20),	--Material Code
	COD_PARCEIRO		VARCHAR(15),	--Customer/Vendor
	DTA_ENTRADA_LOTE	DATE,			--Entry Date of Batch
	COD_LOTE			VARCHAR(15),	--Batch
	VLR_CUSTO_ESTOQUE	NUMERIC(17,3),	--Stock Value
	QTD_ESTOQUE			NUMERIC(17,3),	--Stock Quantity
	QTD_QUILO			NUMERIC(17,3),	--Total Weight
	QTD_VENDA			NUMERIC(17,3),	--Sale Quantity
	VLR_VENDA			NUMERIC(17,3),	--Sale Value
	UND_ESTOQUE			VARCHAR(05),	--Stock Unit
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_MOV_ESTOQUE_MENSAL PRIMARY KEY (IDE_STAGING)
	);


DROP TABLE dbo.HST_P2P_MOV_ESTOQUE_MENSAL;
CREATE TABLE dbo.HST_P2P_MOV_ESTOQUE_MENSAL (
	COD_PLANTA			VARCHAR(05),	--Plant
	COD_CLASSIF			VARCHAR(02),	--Material Type
	DTA_CORTE			DATE,			--Process Date
	COD_ALMOXARIFADO	VARCHAR(05),	--Storage Location
	COD_MATERIAL		VARCHAR(20),	--Material Code
	COD_PARCEIRO		VARCHAR(15),	--Customer/Vendor
	DTA_ENTRADA_LOTE	DATE,			--Entry Date of Batch
	COD_LOTE			VARCHAR(15),	--Batch
	VLR_CUSTO_ESTOQUE	NUMERIC(17,3),	--Stock Value
	QTD_ESTOQUE			NUMERIC(17,3),	--Stock Quantity
	QTD_QUILO			NUMERIC(17,3),	--Total Weight
	QTD_VENDA			NUMERIC(17,3),	--Sale Quantity
	VLR_VENDA			NUMERIC(17,3),	--Sale Value
	UND_ESTOQUE			VARCHAR(05)	--Stock Unit
	);

	CREATE INDEX IX_HST_P2P_MOV_ESTOQUE_MENSAL_01 ON HST_P2P_MOV_ESTOQUE_MENSAL (COD_PLANTA, DTA_CORTE);

DROP TABLE dbo.FAT_P2P_MOV_ESTOQUE_MENSAL;
CREATE TABLE dbo.FAT_P2P_MOV_ESTOQUE_MENSAL (
	COD_EMPRESA			VARCHAR(05),
	COD_PROFIT			VARCHAR(05),
	COD_PLANTA			VARCHAR(05),	--Plant
	COD_CLASSIF			VARCHAR(02),	--Material Type
	DTA_CORTE			DATE,			--Process Date
	COD_ALMOXARIFADO	VARCHAR(05),	--Storage Location
	COD_MATERIAL		VARCHAR(20),	--Material Code
	COD_PARCEIRO		VARCHAR(15),	--Customer/Vendor
	DTA_ENTRADA_LOTE	DATE,			--Entry Date of Batch
	COD_LOTE			VARCHAR(15),	--Batch
	VLR_CUSTO_ESTOQUE	NUMERIC(17,3),	--Stock Value
	QTD_ESTOQUE			NUMERIC(17,3),	--Stock Quantity
	QTD_QUILO			NUMERIC(17,3),	--Total Weight
	QTD_VENDA			NUMERIC(17,3),	--Sale Quantity
	VLR_VENDA			NUMERIC(17,3),	--Sale Value
	UND_ESTOQUE			VARCHAR(05),	--Stock Unit
	COD_AGING			VARCHAR(02),
	COD_TIP_MATERIAL	VARCHAR(05),
	IDE_MATERIAL		BIGINT,
	IDE_CLIENTE			BIGINT,
	IDE_LOTE			BIGINT,
	IDE_ALMOXARIFADO	INT
	);

	CREATE INDEX IX_FAT_P2P_MOV_ESTOQUE_MENSAL_01 ON FAT_P2P_MOV_ESTOQUE_MENSAL (COD_PLANTA, DTA_CORTE);


DROP TABLE dbo.DIM_P2P_CLASSIF_GERENCIAL;
CREATE TABLE dbo.DIM_P2P_CLASSIF_GERENCIAL (
	IDE_CLASSIF_GER		INT IDENTITY,
	COD_CLASSIF			VARCHAR(02),
	DES_CLASSIF			VARCHAR(50)
	);

	INSERT INTO dbo.DIM_P2P_CLASSIF_GERENCIAL VALUES ('MP','MATERIA PRIMA');
	INSERT INTO dbo.DIM_P2P_CLASSIF_GERENCIAL VALUES ('NI','NAO INFORMADO');
	INSERT INTO dbo.DIM_P2P_CLASSIF_GERENCIAL VALUES ('PA','PRODUTO ACABADO');
	INSERT INTO dbo.DIM_P2P_CLASSIF_GERENCIAL VALUES ('OU','OUTROS');
	INSERT INTO dbo.DIM_P2P_CLASSIF_GERENCIAL VALUES ('PC','EM PROCESSO');


DROP TABLE dbo.DIM_P2P_AGING;
CREATE TABLE dbo.DIM_P2P_AGING (
	IDE_AGING	INT IDENTITY,
	COD_AGING	VARCHAR(02),
	DES_AGING	VARCHAR(50)
	);

	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FG','0 A 30 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FF','31 A 60 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FE','61 A 90 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FD','91 A 120 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FC','121 A 150 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FB','151 A 180 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FL','181 A 210 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FM','211 A 240 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FN','241 A 270 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FO','271 A 300 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FP','301 A 330 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FQ','331 A 360 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('FK','ACIMA DE 361 (-)');
	INSERT INTO dbo.DIM_P2P_AGING VALUES ('XX','NAO INFORMADO');

DROP TABLE dbo.TXT_P2P_CAD_MATERIAL;
CREATE TABLE dbo.TXT_P2P_CAD_MATERIAL (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_MATERIAL		VARCHAR(250),	--Material Number
	COD_PLANTA			VARCHAR(250),	--Plant
	DES_MATERIAL_EN		VARCHAR(250),	--Material Description (EN)
	DES_MATERIAL_PT		VARCHAR(250),	--Material Description (PT)
	COD_UND_BASC		VARCHAR(250),	--Unidade basica de medida
	COD_GRP_MERCADO		VARCHAR(250),	--Grupo Material
	COD_SETOR_ATIVIDADE	VARCHAR(250),	--Divisao (Setor Atividade)
	COD_TIP_MATERIAL	VARCHAR(250),	--Tipo Material
	STA_MATERIAL		VARCHAR(250),	--X-Plant Material Status
	DTA_VALIDADE		VARCHAR(250),	--Valid From
	VLR_PESO_BRUTO		VARCHAR(250),	--Peso Bruto (Gross weight)
	UND_PESO			VARCHAR(250),	--Und Peso (Weight Unit)
	VLR_PESO_LIQUIDO	VARCHAR(250),	--Peso Liquido (Net Weight)
	VLR_VOLUME			VARCHAR(250),	--Volume
	UND_VOLUME			VARCHAR(250),	--Und Volume
	VLR_DIMENSAO		VARCHAR(250),	--Tamanho /Dimensao (Size/Dimensions)
	COD_EAN_UPC			VARCHAR(250),	--EAN/UPC
	COD_CTG_EAN			VARCHAR(250),	--EAN Categoria
	COD_GRP_PKG_MAT		VARCHAR(250),	--Grupo Pacote Material (Matl Grp Pack.Matls)
	COD_HIERARQUIA		VARCHAR(250),	--Hierarquia Produto (Product Hierarchy)
	COD_GRP_TRANSPORTE	VARCHAR(250),	--Grupo Trans (Trans grp)
	COD_GER_LOTE		VARCHAR(250),	--Gerenciamento Lote (Batch management)
	COD_AD_LOT_OBRI		VARCHAR(250),	--AdLotObri (Min rem shelf life)
	NUM_PRAZO_VALIDADE	VARCHAR(250),	--PrzValid (Total shelf life)
	COD_SUPRIM_QM		VARCHAR(250),	--Suprim-QM (QM proc Active)
	COD_GRP_FRETE_MAT	VARCHAR(250),	--Grupo Frete Material (Material freight grp)
	COD_VERIF_DISP		VARCHAR(250),	--VerifDisp (Availability check)
	VLR_TEMPO_PREP		VARCHAR(250),	--Tempo Setup (Setup time)
	VLR_TEMPO_PROC		VARCHAR(250),	--Tempo Processo (Proc time)
	COD_GRP_CARREG		VARCHAR(250),	--Grupo Carregamento (LoadingGrp)
	QTD_BASE			VARCHAR(250),	--Quantidade Base (Base qty)
	COD_COMEX			VARCHAR(250),	--Código COMEX (Comm/Imp Code No.)
	GRP_COMEX			VARCHAR(250),	--Grupo COMEX (Export/Import group)
	NUM_PRODCOM			VARCHAR(250),	--PRODCOM No
	COD_CONTROLE		VARCHAR(250),	--Código Controle (Control Code)
	COD_ORIGEM			VARCHAR(250),	--Local Origem (Country of origin)
	COD_REGIAO_ORIGEM	VARCHAR(250),	--Região Origem (Region of origin)
	NUM_LISTA_PRM		VARCHAR(250),	--Numero Lista Produto (CAP Product List No.)
	CAP_GRP_PRM			VARCHAR(250),	--Grupo Produto (CAP Prod Group)
	COD_CERTIF_ISENCAO	VARCHAR(250),	--Certificado Isencao (ExemptionCertificate)
	NUM_CERTIF_ISENCAO	VARCHAR(250),	--Número Certif Isencao (Exemption Cert No.)
	DTA_CERTIF_ISENCAO	VARCHAR(250),	--Data Certificado Isencao (Iss Date of Ex cert)
	COD_MAT_CTG_CFOP	VARCHAR(250),	--Categoria CFOP Material (Mat CFOP category)
	COD_GRP_COMPRAS		VARCHAR(250),	--Grupo Compras (Purchasing Group)
	STA_MATERIAL1		VARCHAR(250),	--Status Material Planta (Plant-sp Matl Status)
	DTA_VALIDADE_1		VARCHAR(250),	--Validade Origem (Valid From)
	COD_PED_AUT			VARCHAR(250),	--Pedido Autom (Autom PO)
	COD_TMPO_PROC_EM	VARCHAR(250),	--TmpoProcEM (GR Processing Time)
	COD_UTIL_QUOTIZ		VARCHAR(250),	--UtilQuotiz (Quota Arr Usage)
	COD_LISTA_ORIGEM	VARCHAR(250),	--Lista Origem (Source List)
	COD_CONTROLE_1		VARCHAR(250),	--(Control Code)
	COD_GRP_MRP			VARCHAR(250),	--GrupoMRP (MRP group)
	COD_ABC				VARCHAR(250),	--CódigoABC (ABC indicator)
	COD_TIP_MRP			VARCHAR(250),	--TpMRP (MRP Type)
	QTD_PTO_REABAST		VARCHAR(250),	--Pt.Reabast (Reorder Point)
	COD_PLJ_MRP			VARCHAR(250),	--PljMRP (MRP Controller)
	NUM_TAM_LOTE_MRP	VARCHAR(250),	--TamLtMRP (Lot size)
	NUM_TAM_MIN_LOTE	VARCHAR(250),	--TamMinLote (Minimum lot size)
	NUM_TAM_MAX_LOTE	VARCHAR(250),	--TamMáxLote (Maximum lot size)
	QTD_MAX_ESTOQUE		VARCHAR(250),	--EstoqueMáx (Maximum stock level)
	COD_TIP_SUP			VARCHAR(250),	--TipSup (Procurement type)
	COD_TIP_SUP_ESPEC	VARCHAR(250),	--TpSupEs (Special procurement)
	COD_LOCAL_STORE		VARCHAR(250),	--DepPro (Prod Stor Location)
	NUM_PRZ_ENTR_PR		VARCHAR(250),	--PrzEntrPr (Plnd Delivery Time)
	QTD_SEGURO_ESTOQUE	VARCHAR(250),	--EstqSeg (Safety Stock)
	COD_SELEC_ALTER		VARCHAR(250),	--SeleçAlter (Selection Method)
	PRC_COMP_REFUG		VARCHAR(250),	--RefugComp (Component scrap (%))
	COD_INDIV_COL		VARCHAR(250),	--Indiv/col (Individual/Coll)
	COD_PROD_REP		VARCHAR(250),	--ProdRep (Repetitive Mfg)
	COD_PERFIL_REM		VARCHAR(250),	--PerfProdRe (REM Profile)
	COD_VERSAO			VARCHAR(250),	--Versão (Version Indicator)
	COD_UM_SAIDA		VARCHAR(250),	--UMSaída (Unit of issue :: UND_VENDA????)
	COD_INV_ROTAT		VARCHAR(250),	--Inv.Rotat (CC Phys Inv Ind)
	COD_CC_FIXO			VARCHAR(250),	--CC fixo (CC fixed)
	COD_UNID_TEMP		VARCHAR(250),	--Unidade Tempo (Time unit)
	COD_GDE				VARCHAR(250),	--GDE (Stock Determ Group)
	COD_QLD_ESTOQUE		VARCHAR(250),	--EstqQld (Post to Insp Stock)
	COD_QM_AUTMAT		VARCHAR(250),	--QM AutMat (QM Material Auth)
	COD_QM_CHAVE_CTRL	VARCHAR(250),	--ChavCtrlQM (QM Control Key)
	COD_TIPO_CERTIF		VARCHAR(250),	-- (Certificate type)
	COD_PROFIT_CENTER	VARCHAR(250),	--Ctg.cert. (Profit Center)
	COD_CO_PROD			VARCHAR(250),	--Co-prod (Co-product)
	COD_AREA_AVAL		VARCHAR(250),	--Área aval (Valuation Area)
	COD_CLASSE_AVAL		VARCHAR(250),	--ClassAval (Valuation Class)
	VLR_PRC_STANDARD	VARCHAR(250),	--Prç stand (Standard Price)
	UND_PRECO			VARCHAR(250),	--Un preço (Price Unit)
	COD_LM_ATIVO		VARCHAR(250),	--LMativo (ML Act)
	COD_CALC_EST		VARCHAR(250),	--Calc Est (With Qty Structure)
	COD_GRP_ORIGINAL	VARCHAR(250),	--(Origin Group)
	VLR_PRC_PLAN		VARCHAR(250),	--Preco Planejado (Planned Price)
	VLR_CLASSE_AVAL_1	VARCHAR(250),	--Class Aval (Valuation Class)
	COD_CTRL_PRECO		VARCHAR(250),	--CtrlPrç (Price Control)
	VLR_PRC_MOVEL		VARCHAR(250),	--Preco Movel (Moving Price)
	VLR_PRC_PLAN_ANT	VARCHAR(250),	--Preco Planejado Anterior (Previous Planned Price)
	COD_DET_PRECO		VARCHAR(250),	--DetTar (Price Determ)
	COD_POSDPST			VARCHAR(250),	--Storage Bin
	COD_NV1_HIERARQUIA	VARCHAR(250),	--HrqNv1
	DES_NV1_HIERARQUIA	VARCHAR(250),	--Nome
	COD_NV2_HIERARQUIA	VARCHAR(250),	--HrqNv2
	DES_NV2_HIERARQUIA	VARCHAR(250),	--Nome
	COD_NV3_HIERARQUIA	VARCHAR(250),	--HrqNv3
	DES_NV3_HIERARQUIA	VARCHAR(250),	--Nome
	COD_NV4_HIERARQUIA	VARCHAR(250),	--HrqNv4
	DES_NV4_HIERARQUIA	VARCHAR(250),	--Nome
	COD_NV5_HIERARQUIA	VARCHAR(250),	--HrqNv5
	DES_NV5_HIERARQUIA	VARCHAR(250),	--Nome
	COD_NV6_HIERARQUIA	VARCHAR(250),	--HrqNv6
	DES_NV6_HIERARQUIA	VARCHAR(250),	--Nome
	COD_GRP_MATERIAL1	VARCHAR(250),	--GpMat1
	DES_GRP_MATERIAL1	VARCHAR(250),	--Nome
	COD_GRP_MATERIAL2	VARCHAR(250),	--GpMat2
	DES_GRP_MATERIAL2	VARCHAR(250),	--Nome
	COD_GRP_MATERIAL3	VARCHAR(250),	--GpMat3
	DES_GRP_MATERIAL3	VARCHAR(250),	--Nome
	COD_GRP_MATERIAL4	VARCHAR(250),	--GpMat4
	DES_GRP_MATERIAL4	VARCHAR(250),	--Nome
	COD_GRP_MATERIAL5	VARCHAR(250),	--GpMat5
	DES_GRP_MATERIAL5	VARCHAR(250),	--Nome
	);

TRUNCATE TABLE dbo.TXT_P2P_CAD_MATERIAL
SELECT * FROM dbo.TXT_P2P_CAD_MATERIAL

DROP TABLE dbo.STG_P2P_CAD_MATERIAL;
CREATE TABLE dbo.STG_P2P_CAD_MATERIAL (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_MATERIAL		VARCHAR(20),	--COD_MATERIAL
	COD_PLANTA			VARCHAR(05),	--COD_PLANTA
	DES_MATERIAL_EN		VARCHAR(100),	--Material Description (EN)
	DES_MATERIAL_PT		VARCHAR(100),	--Material Description (PT)
	COD_UND_BASC		VARCHAR(05),	--Unidade basica de medida
	COD_GRP_MERCADO		VARCHAR(50),	--Grupo Material
	COD_SETOR_ATIVIDADE	VARCHAR(02),	--Divisao (Setor Atividade)
	COD_TIP_MATERIAL	VARCHAR(05),	--Tipo Material
	STA_MATERIAL		VARCHAR(02),	--X-Plant Material Status
	DTA_VALIDADE		DATE,			--Valid From
	VLR_PESO_BRUTO		NUMERIC(17,3),	--Peso Bruto (Gross weight)
	UND_PESO			VARCHAR(02),	--Und Peso (Weight Unit)
	VLR_PESO_LIQUIDO	NUMERIC(17,3),	--Peso Liquido (Net Weight)
	VLR_VOLUME			NUMERIC(17,3),	--Volume
	UND_VOLUME			VARCHAR(20),	--Und Volume
	VLR_DIMENSAO		VARCHAR(20),	--Tamanho /Dimensao (Size/Dimensions)
	COD_EAN_UPC			VARCHAR(20),	--EAN/UPC
	COD_CTG_EAN			VARCHAR(20),	--EAN Categoria
	COD_GRP_PKG_MAT		VARCHAR(20),	--Grupo Pacote Material (Matl Grp Pack.Matls)
	COD_HIERARQUIA		VARCHAR(20),	--Hierarquia Produto (Product Hierarchy)
	COD_GRP_TRANSPORTE	VARCHAR(20),	--Grupo Trans (Trans grp)
	COD_GER_LOTE		VARCHAR(20),	--Gerenciamento Lote (Batch management)
	COD_AD_LOT_OBRI		VARCHAR(20),	--AdLotObri (Min rem shelf life)
	NUM_PRAZO_VALIDADE	INT,			--PrzValid (Total shelf life)
	COD_SUPRIM_QM		VARCHAR(20),	--Suprim-QM (QM proc Active)
	COD_GRP_FRETE_MAT	VARCHAR(20),	--Grupo Frete Material (Material freight grp)
	COD_VERIF_DISP		VARCHAR(20),	--VerifDisp (Availability check)
	VLR_TEMPO_PREP		NUMERIC(17,3),	--Tempo Setup (Setup time)
	VLR_TEMPO_PROC		NUMERIC(17,3),	--Tempo Processo (Proc time)
	COD_GRP_CARREG		VARCHAR(20),	--Grupo Carregamento (LoadingGrp)
	QTD_BASE			NUMERIC(17,3),	--Quantidade Base (Base qty)
	COD_COMEX			VARCHAR(20),	--Código COMEX (Comm/Imp Code No.)
	GRP_COMEX			VARCHAR(20),	--Grupo COMEX (Export/Import group)
	NUM_PRODCOM			INT,			--PRODCOM No
	COD_CONTROLE		VARCHAR(20),	--Código Controle (Control Code)
	COD_ORIGEM			VARCHAR(02),	--Local Origem (Country of origin)
	COD_REGIAO_ORIGEM	VARCHAR(20),	--Região Origem (Region of origin)
	NUM_LISTA_PRM		VARCHAR(20),	--Numero Lista Produto (CAP Product List No.)
	CAP_GRP_PRM			VARCHAR(20),	--Grupo Produto (CAP Prod Group)
	COD_CERTIF_ISENCAO	VARCHAR(20),	--Certificado Isencao (ExemptionCertificate)
	NUM_CERTIF_ISENCAO	VARCHAR(20),	--Número Certif Isencao (Exemption Cert No.)
	DTA_CERTIF_ISENCAO	DATE,			--Data Certificado Isencao (Iss Date of Ex cert)
	COD_MAT_CTG_CFOP	VARCHAR(20),	--Categoria CFOP Material (Mat CFOP category)
	COD_GRP_COMPRAS		VARCHAR(20),	--Grupo Compras (Purchasing Group)
	STA_MATERIAL1		VARCHAR(20),	--Status Material Planta (Plant-sp Matl Status)
	DTA_VALIDADE_1		DATE,			--Validade Origem (Valid From)
	COD_PED_AUT			VARCHAR(20),	--Pedido Autom (Autom PO)
	COD_TMPO_PROC_EM	VARCHAR(20),	--TmpoProcEM (GR Processing Time)
	COD_UTIL_QUOTIZ		VARCHAR(20),	--UtilQuotiz (Quota Arr Usage)
	COD_LISTA_ORIGEM	VARCHAR(20),	--Lista Origem (Source List)
	COD_CONTROLE_1		VARCHAR(20),	--Código Controle (Control Code)
	COD_GRP_MRP			VARCHAR(20),	--GrupoMRP (MRP group)
	COD_ABC				VARCHAR(20),	--CódigoABC (ABC indicator)
	COD_TIP_MRP			VARCHAR(20),	--TpMRP (MRP Type)
	QTD_PTO_REABAST		NUMERIC(17,3),	--Pt.Reabast (Reorder Point)
	COD_PLJ_MRP			VARCHAR(20),	--PljMRP (MRP Controller)
	NUM_TAM_LOTE_MRP	VARCHAR(20),	--TamLtMRP (Lot size)
	NUM_TAM_MIN_LOTE	NUMERIC(17,3),	--TamMinLote (Minimum lot size)
	NUM_TAM_MAX_LOTE	NUMERIC(17,3),	--TamMáxLote (Maximum lot size)
	QTD_MAX_ESTOQUE		NUMERIC(17,3),	--EstoqueMáx (Maximum stock level)
	COD_TIP_SUP			VARCHAR(20),	--TipSup (Procurement type)
	COD_TIP_SUP_ESPEC	VARCHAR(20),	--TpSupEs (Special procurement)
	COD_LOCAL_STORE		VARCHAR(20),	--DepPro (Prod Stor Location)
	NUM_PRZ_ENTR_PR		INT,			--PrzEntrPr (Plnd Delivery Time)
	QTD_SEGURO_ESTOQUE	NUMERIC(17,3),	--EstqSeg (Safety Stock)
	COD_SELEC_ALTER		VARCHAR(20),	--SeleçAlter (Selection Method)
	PRC_COMP_REFUG		NUMERIC(17,3),	--RefugComp (Component scrap (%))
	COD_INDIV_COL		VARCHAR(20),	--Indiv/col (Individual/Coll)
	COD_PROD_REP		VARCHAR(20),	--ProdRep (Repetitive Mfg)
	COD_PERFIL_REM		VARCHAR(20),	--PerfProdRe (REM Profile)
	COD_VERSAO			VARCHAR(20),	--Versão (Version Indicator)
	COD_UM_SAIDA		VARCHAR(20),	--UMSaída (Unit of issue :: UND_VENDA????)
	COD_INV_ROTAT		VARCHAR(20),	--Inv.Rotat (CC Phys Inv Ind)
	COD_CC_FIXO			VARCHAR(20),	--CC fixo (CC fixed)
	COD_UNID_TEMP		VARCHAR(20),	--Unidade Tempo (Time unit)
	COD_GDE				VARCHAR(20),	--GDE (Stock Determ Group)
	COD_QLD_ESTOQUE		VARCHAR(20),	--EstqQld (Post to Insp Stock)
	COD_QM_AUTMAT		VARCHAR(20),	--QM AutMat (QM Material Auth)
	COD_QM_CHAVE_CTRL	VARCHAR(20),	--ChavCtrlQM (QM Control Key)
	COD_TIPO_CERTIF		VARCHAR(20),	--(Certificate type)
	COD_PROFIT_CENTER	VARCHAR(20),	--Ctg.cert. (Profit Center)
	COD_CO_PROD			VARCHAR(20),	--Co-prod (Co-product)
	COD_AREA_AVAL		VARCHAR(05),	--Área aval (Valuation Area)
	COD_CLASSE_AVAL		VARCHAR(20),	--ClassAval (Valuation Class)
	VLR_PRC_STANDARD	NUMERIC(17,3),	--Prç stand (Standard Price)
	UND_PRECO			VARCHAR(20),	--Un preço (Price Unit)
	COD_LM_ATIVO		VARCHAR(20),	--LMativo (ML Act)
	COD_CALC_EST		VARCHAR(20),	--Calc Est (With Qty Structure)
	COD_GRP_ORIGINAL	VARCHAR(20),	--(Origin Group)
	VLR_PRC_PLAN		NUMERIC(17,3),	--Preco Planejado (Planned Price)
	VLR_CLASSE_AVAL_1	VARCHAR(20),	--Class Aval (Valuation Class)
	COD_CTRL_PRECO		VARCHAR(20),	--CtrlPrç (Price Control)
	VLR_PRC_MOVEL		NUMERIC(17,3),	--Preco Movel (Moving Price)
	VLR_PRC_PLAN_ANT	NUMERIC(17,3),	--Preco Planejado Anterior (Previous Planned Price)
	COD_DET_PRECO		NUMERIC(17,3),	--DetTar (Price Determ)
	COD_POSDPST			VARCHAR(20),	--Storage Bin
	COD_NV1_HIERARQUIA	VARCHAR(20),	--COD_NV1_HIERARQUIA
	DES_NV1_HIERARQUIA	VARCHAR(50),	--DES_NV1_HIERARQUIA
	COD_NV2_HIERARQUIA	VARCHAR(20),	--COD_NV2_HIERARQUIA
	DES_NV2_HIERARQUIA	VARCHAR(50),	--DES_NV2_HIERARQUIA
	COD_NV3_HIERARQUIA	VARCHAR(20),	--COD_NV3_HIERARQUIA
	DES_NV3_HIERARQUIA	VARCHAR(50),	--DES_NV3_HIERARQUIA
	COD_NV4_HIERARQUIA	VARCHAR(20),	--COD_NV4_HIERARQUIA
	DES_NV4_HIERARQUIA	VARCHAR(50),	--DES_NV4_HIERARQUIA
	COD_NV5_HIERARQUIA	VARCHAR(20),	--COD_NV5_HIERARQUIA
	DES_NV5_HIERARQUIA	VARCHAR(50),	--DES_NV5_HIERARQUIA
	COD_NV6_HIERARQUIA	VARCHAR(20),	--COD_NV6_HIERARQUIA
	DES_NV6_HIERARQUIA	VARCHAR(50),	--DES_NV6_HIERARQUIA
	COD_GRP_MATERIAL1	VARCHAR(20),	--COD_GRP_MATERIAL1
	DES_GRP_MATERIAL1	VARCHAR(50),	--DES_GRP_MATERIAL1
	COD_GRP_MATERIAL2	VARCHAR(20),	--COD_GRP_MATERIAL2
	DES_GRP_MATERIAL2	VARCHAR(50),	--DES_GRP_MATERIAL2
	COD_GRP_MATERIAL3	VARCHAR(20),	--COD_GRP_MATERIAL3
	DES_GRP_MATERIAL3	VARCHAR(50),	--DES_GRP_MATERIAL3
	COD_GRP_MATERIAL4	VARCHAR(20),	--COD_GRP_MATERIAL4
	DES_GRP_MATERIAL4	VARCHAR(50),	--DES_GRP_MATERIAL4
	COD_GRP_MATERIAL5	VARCHAR(20),	--COD_GRP_MATERIAL5
	DES_GRP_MATERIAL5	VARCHAR(50),	--DES_GRP_MATERIAL5
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_MATERIAL PRIMARY KEY (IDE_STAGING)
	);

TRUNCATE TABLE dbo.STG_P2P_CAD_MATERIAL
SELECT * FROM dbo.STG_P2P_CAD_MATERIAL

sp_columns DIM_SAP_MATERIAL
SELECT TOP 10 * FROM DIM_SAP_MATERIAL


DROP TABLE dbo.TXT_P2P_CAD_ALMOXARIFADO;
CREATE TABLE dbo.TXT_P2P_CAD_ALMOXARIFADO (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),
	COD_ALMOXARIFADO	VARCHAR(50),
	DES_ALMOXARIFADO	VARCHAR(50)
	);

TRUNCATE TABLE dbo.TXT_P2P_CAD_ALMOXARIFADO
SELECT * FROM dbo.STG_P2P_CAD_ALMOXARIFADO

DROP TABLE dbo.STG_P2P_CAD_ALMOXARIFADO;
CREATE TABLE dbo.STG_P2P_CAD_ALMOXARIFADO (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(05),
	COD_ALMOXARIFADO	VARCHAR(05),
	DES_ALMOXARIFADO	VARCHAR(50),
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_ALMOXARIFADO PRIMARY KEY (IDE_STAGING)
	);

DROP TABLE dbo.DIM_SAP_ALMOXARIFADO;
CREATE TABLE dbo.DIM_SAP_ALMOXARIFADO (
	IDE_ALMOXARIFADO	INT IDENTITY,
	COD_EMPRESA			VARCHAR(05),
	COD_PROFIT			VARCHAR(05),
	COD_PLANTA			VARCHAR(05),
	COD_ALMOXARIFADO	VARCHAR(05),
	DES_ALMOXARIFADO	VARCHAR(50)
	);

	CREATE INDEX IX_DIM_SAP_ALMOXARIFADO_01 ON DIM_SAP_ALMOXARIFADO (COD_EMPRESA, COD_PROFIT, COD_PLANTA, COD_ALMOXARIFADO);


DROP TABLE dbo.DIM_P2P_CAD_LOTE;
CREATE TABLE dbo.DIM_P2P_CAD_LOTE (
	IDE_LOTE			BIGINT IDENTITY,
	COD_PLANTA			VARCHAR(05),
	COD_LOTE			VARCHAR(15),
	DTA_ENTRADA			DATE,
	DES_LOTE			VARCHAR(50),
	COD_LOTE_LEGADO		VARCHAR(15) DEFAULT 'NDA LEGADO'
	);

	ALTER TABLE DIM_P2P_CAD_LOTE ADD COD_LOTE_LEGADO VARCHAR(15) DEFAULT 'NDA LEGADO';

	CREATE INDEX IX_DIM_P2P_CAD_LOTE_01 ON DIM_P2P_CAD_LOTE (COD_PLANTA, COD_LOTE, DTA_ENTRADA);

-- DADOS SERVIDOR TESTE ds191050t\baanarg (ttdilb105310)
DROP TABLE dbo.TMP_P2P_CAD_LOTE_LEGADO;
CREATE TABLE dbo.TMP_P2P_CAD_LOTE_LEGADO (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),	--t_plas_c
	COD_MATERIAL_SAP	VARCHAR(50),	--t_itms_c
	DES_MATERIAL_SAP	VARCHAR(50),	--t_dscs_c
	COD_MATERIAL_BAAN	VARCHAR(50),	--t_item_c
	COD_LOTE_SAP		VARCHAR(50),	--t_lots_c
	COD_LOTE_BAAN		VARCHAR(50),	--t_clot_c
	DTA_ENTRADA_LOTE	DATE,			--t_dtpe_c
	DTA_LANCAM_LOTE		DATE,			--t_dlan_c
	COD_FORNECEDOR		VARCHAR(50),	--t_lfos_c
	COD_LOTE_FOR		VARCHAR(50)		--t_lotf_c
	);

DROP TABLE dbo.STG_P2P_CAD_LOTE_LEGADO;
CREATE TABLE dbo.STG_P2P_CAD_LOTE_LEGADO (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(04),
	COD_MATERIAL_SAP	VARCHAR(20),
	DES_MATERIAL_SAP	VARCHAR(50),
	COD_MATERIAL_BAAN	VARCHAR(20),
	COD_LOTE_SAP		VARCHAR(15),
	COD_LOTE_BAAN		VARCHAR(15),
	DTA_ENTRADA_LOTE	DATE,
	DTA_LANCAM_LOTE		DATE,
	COD_FORNECEDOR		VARCHAR(10),
	COD_LOTE_FOR		VARCHAR(15),
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_LOTE_LEGADO PRIMARY KEY (IDE_STAGING)
	);

	CREATE INDEX IX_STG_P2P_CAD_LOTE_LEGADO_01 ON STG_P2P_CAD_LOTE_LEGADO (COD_PLANTA,COD_MATERIAL_SAP,COD_LOTE_SAP,DTA_ENTRADA_LOTE);

UPDATE DIM_P2P_CAD_LOTE
	SET	COD_LOTE_LEGADO=CAD.COD_LOTE_LEGADO
FROM
	STG_P2P_CAD_LOTE_LEGADO CAD
WHERE
	DIM_P2P_CAD_LOTE.COD_PLANTA=CAD.COD_PLANTA AND
	DIM_P2P_CAD_LOTE.COD_LOTE=CAD.COD_LOTE


UPDATE DIM_P2P_CAD_LOTE
	SET COD_LOTE_LEGADO='NDA LEGADO'
WHERE
	COD_LOTE_LEGADO IS NULL


DROP TABLE dbo.TXT_P2P_CAD_FORNECEDOR;
CREATE TABLE dbo.TXT_P2P_CAD_FORNECEDOR (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_FORNECEDOR		VARCHAR(50),	--Column 0
	DES_FORNECEDOR		VARCHAR(50),	--Column 1
	CHV_FORNECEDOR		VARCHAR(50),	--Column 2
	DES_ENDERECO		VARCHAR(50),	--Column 3
	DES_BAIRRO			VARCHAR(50),	--Column 4
	DES_CIDADE			VARCHAR(50),	--Column 5
	NUM_CEP				VARCHAR(50),	--Column 6
	DES_ESTADO			VARCHAR(50),	--Column 7
	DES_PAIS			VARCHAR(50),	--Column 8
	NUM_CNPJ			VARCHAR(50),	--Column 9
	NUM_TELEFONE		VARCHAR(50),	--Column 10
	DTA_CRIACAO			VARCHAR(50),	--Column 11
	GRP_FINANCEIRO		VARCHAR(50),	--Column 12
	DES_ORG_COMPRAS		VARCHAR(50)		--Column 13
	);

DROP TABLE dbo.STG_P2P_CAD_FORNECEDOR;
CREATE TABLE dbo.STG_P2P_CAD_FORNECEDOR (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_FORNECEDOR		VARCHAR(10),
	DES_FORNECEDOR		VARCHAR(50),
	CHV_FORNECEDOR		VARCHAR(20),
	DES_ENDERECO		VARCHAR(50),
	DES_BAIRRO			VARCHAR(50),
	DES_CIDADE			VARCHAR(50),
	NUM_CEP				VARCHAR(15),
	DES_ESTADO			VARCHAR(02),
	DES_PAIS			VARCHAR(02),
	NUM_CNPJ			VARCHAR(15),
	NUM_TELEFONE		VARCHAR(15),
	DTA_CRIACAO			DATE,
	GRP_FINANCEIRO		VARCHAR(15),
	DES_ORG_COMPRAS		VARCHAR(50),
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_FORNECEDOR PRIMARY KEY (IDE_STAGING)
	);


DROP TABLE dbo.DIM_SAP_FORNECEDOR;
CREATE TABLE dbo.DIM_SAP_FORNECEDOR (
	IDE_FORNECEDOR		BIGINT IDENTITY,
	COD_FORNECEDOR		VARCHAR(10),
	DES_FORNECEDOR		VARCHAR(50),
	CHV_FORNECEDOR		VARCHAR(20),
	DES_ENDERECO		VARCHAR(50),
	DES_BAIRRO			VARCHAR(50),
	DES_CIDADE			VARCHAR(50),
	NUM_CEP				VARCHAR(15),
	DES_ESTADO			VARCHAR(02),
	DES_PAIS			VARCHAR(02),
	NUM_CNPJ			VARCHAR(15),
	NUM_TELEFONE		VARCHAR(15),
	DTA_CRIACAO			DATE,
	GRP_FINANCEIRO		VARCHAR(15),
	DES_ORG_COMPRAS		VARCHAR(50)
	);

	CREATE INDEX IX_DIM_SAP_FORNECEDOR_01 ON DIM_SAP_FORNECEDOR (COD_FORNECEDOR);

SELECT TOP 10 * FROM DIM_SAP_FORNECEDOR
INSERT INTO DIM_SAP_FORNECEDOR VALUES ('0000000000','NAO INFORMADO','NAO INFORMADO','NAO INFORMADO','NAO INFORMADO','NAO INFORMADO','00000-000','XX','XX','','XXX','2018-01-01','XXX','NAO INFORMADO');


DROP TABLE dbo.TXT_P2P_GRUPO_FORNECEDOR;
CREATE TABLE dbo.TXT_P2P_GRUPO_FORNECEDOR (
	IDE_TEMP				INT IDENTITY,
	SKY_AUDITKEY			INT,
	DTA_CARGA				DATETIME,
	COD_GRUPO_FORNECEDOR	VARCHAR(50),	--Column 0
	DES_GRUPO_FORNECEDOR	VARCHAR(50),	--Column 1
	);


DROP TABLE dbo.STG_P2P_GRUPO_FORNECEDOR;
CREATE TABLE dbo.STG_P2P_GRUPO_FORNECEDOR (
	IDE_STAGING				INT IDENTITY,
	SKY_AUDITKEY			INT,
	DTA_CARGA				DATETIME,
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	DES_GRUPO_FORNECEDOR	VARCHAR(50),
	COD_QUALITY				CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_GRUPO_FORNECEDOR PRIMARY KEY (IDE_STAGING)
	);


DROP TABLE dbo.DIM_SAP_GRP_FORNECEDOR;
CREATE TABLE dbo.DIM_SAP_GRP_FORNECEDOR (
	IDE_GRP_FORNECEDOR	INT IDENTITY,
	COD_GRP_FORNECEDOR	VARCHAR(03),
	DES_GRP_FORNECEDOR	VARCHAR(50),
	);

	CREATE INDEX IX_DIM_SAP_GRP_FORNECEDOR_01 ON DIM_SAP_GRP_FORNECEDOR (COD_GRP_FORNECEDOR);

INSERT INTO DIM_SAP_GRP_FORNECEDOR VALUES ('000','NAO INFORMADO');

-- Receber os dados da interface SAP_P2P_MOV_NFISCAL.txt
DROP TABLE dbo.TXT_P2P_MOV_NF_ENTRADA;
CREATE TABLE dbo.TXT_P2P_MOV_NF_ENTRADA (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),	--Column 0
	TIP_NFISCAL			VARCHAR(50),	--Column 1
	DTA_ENTRADA			VARCHAR(50),	--Column 2
	NUM_DOCTO			VARCHAR(50),	--Column 3
	COD_GRP_FORNECEDOR	VARCHAR(50),	--Column 4
	COD_FORNECEDOR		VARCHAR(50),	--Column 5
	COD_MATERIAL		VARCHAR(50),	--Column 6
	COD_ORDEM_COMPRA	VARCHAR(50),	--Column 7
	NUM_ORDEM_ITEM		VARCHAR(50),	--Column 8
	VLR_ITEM			VARCHAR(50),	--Column 9
	QTD_UND_COMPRA		VARCHAR(50),	--Column 10
	QTD_UND_ESTOQUE		VARCHAR(50),	--Column 11
	VLR_IPI				VARCHAR(50),	--Column 12
	VLR_ICMS			VARCHAR(50),	--Column 13
	VLR_PISCOFINS		VARCHAR(50),	--Column 14
	DTA_ENTRADA_FISCAL	VARCHAR(50)		--Column 15
	);

SELECT * FROM TXT_P2P_MOV_NF_ENTRADA

DROP TABLE dbo.STG_P2P_MOV_NF_ENTRADA;
CREATE TABLE dbo.STG_P2P_MOV_NF_ENTRADA (
	IDE_STAGING				INT IDENTITY,
	SKY_AUDITKEY			INT,
	DTA_CARGA				DATETIME,
	COD_PLANTA				VARCHAR(04),
	TIP_NFISCAL				VARCHAR(20),
	DTA_ENTRADA				DATE,
	NUM_DOCTO				VARCHAR(10),
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_FORNECEDOR			VARCHAR(10),
	COD_MATERIAL			VARCHAR(20),
	COD_ORDEM_COMPRA		VARCHAR(10),
	NUM_ORDEM_ITEM			VARCHAR(06),
	VLR_ITEM				NUMERIC(17,3),
	QTD_UND_COMPRA			NUMERIC(17,3),
	QTD_UND_ESTOQUE			NUMERIC(17,3),
	VLR_IPI					NUMERIC(17,3),
	VLR_ICMS				NUMERIC(17,3),
	VLR_PISCOFINS			NUMERIC(17,3),
	DTA_ENTRADA_FISCAL		DATE,
	COD_QUALITY				CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_MOV_NF_ENTRADA PRIMARY KEY (IDE_STAGING)
	);

SELECT * FROM STG_P2P_MOV_NF_ENTRADA

DROP TABLE dbo.HST_P2P_MOV_NF_ENTRADA;
CREATE TABLE dbo.HST_P2P_MOV_NF_ENTRADA (
	COD_PLANTA				VARCHAR(04),
	TIP_NFISCAL				VARCHAR(20),
	DTA_ENTRADA				DATE,
	NUM_DOCTO				VARCHAR(10),
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_FORNECEDOR			VARCHAR(10),
	COD_MATERIAL			VARCHAR(20),
	COD_ORDEM_COMPRA		VARCHAR(10),
	NUM_ORDEM_ITEM			VARCHAR(06),
	VLR_ITEM				NUMERIC(17,3),
	QTD_UND_COMPRA			NUMERIC(17,3),
	QTD_UND_ESTOQUE			NUMERIC(17,3),
	VLR_IPI					NUMERIC(17,3),
	VLR_ICMS				NUMERIC(17,3),
	VLR_PISCOFINS			NUMERIC(17,3),
	DTA_ENTRADA_FISCAL		DATE
	);

	CREATE INDEX IX_HST_P2P_MOV_NF_ENTRADA_01 ON HST_P2P_MOV_NF_ENTRADA (COD_PLANTA, DTA_ENTRADA);

DROP TABLE dbo.FAT_P2P_MOV_NF_ENTRADA;
CREATE TABLE dbo.FAT_P2P_MOV_NF_ENTRADA (
	COD_EMPRESA				VARCHAR(04),	--EMPRESA
	COD_PLANTA				VARCHAR(04),	--PLANTA
	COD_PROFIT_CENTER		VARCHAR(04),	--PROFIT CENTER
	TIP_NFISCAL				VARCHAR(20),
	DTA_ENTRADA				DATE,			--DATA
	NUM_DOCTO				VARCHAR(10),	--DOCTO (NF ENTRADA)
	COD_GRUPO_FORNECEDOR	VARCHAR(03),	--COMPRADOR
	COD_FORNECEDOR			VARCHAR(10),	--FORNECEDOR
	COD_MATERIAL			VARCHAR(20),	--MATERIAL,
	COD_ORDEM_COMPRA		VARCHAR(10),	--ORDEM COMPRA
	NUM_ORDEM_ITEM			VARCHAR(06),	--DOCTO ITEM
	VLR_ITEM				NUMERIC(17,3),	--VLR COMPRA / DEVOLUCAO
	QTD_UND_COMPRA			NUMERIC(17,3),	--QTD UND COMPRA / DEVOLUCAO
	QTD_UND_ESTOQUE			NUMERIC(17,3),	--QTD UND ESTOQUE / DEVOLUCAO
	VLR_IPI					NUMERIC(17,3),	--VLR IPI (LIQUIDO)
	VLR_ICMS				NUMERIC(17,3),	--VLR ICMS (LIQUIDO)
	VLR_PISCOFINS			NUMERIC(17,3),	--VLR PISCOFINS (LIQUIDO)
	DTA_ENTRADA_FISCAL		DATE,
	TIP_ITEM				CHAR(01),		--MATERIAL OU SERVICO
	IDE_NF_ENTRADA			BIGINT,
	IDE_ORDEM_COMPRA		BIGINT,
	IDE_FORNECEDOR			BIGINT,
	IDE_MATERIAL			BIGINT,
	IDE_SERVICO				BIGINT
	);

	CREATE INDEX IX_FAT_P2P_MOV_NF_ENTRADA_01 ON FAT_P2P_MOV_NF_ENTRADA (COD_PLANTA, DTA_ENTRADA);

	TRUNCATE TABLE FAT_P2P_MOV_NF_ENTRADA

-- Receber os dados da interface SAP_P2P_MOV_OCOMPRAS.txt
DROP TABLE dbo.TXT_P2P_MOV_ORDEM_COMPRA;
CREATE TABLE dbo.TXT_P2P_MOV_ORDEM_COMPRA (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),	--Column 0
	DTA_ENTREGA			VARCHAR(50),	--Column 1
	STA_ORDEM			VARCHAR(50),	--Column 2
	COD_GRP_FORNECEDOR	VARCHAR(50),	--Column 3
	COD_FORNECEDOR		VARCHAR(50),	--Column 4
	COD_MATERIAL		VARCHAR(50),	--Column 5
	COD_SOLIC_COMPRA	VARCHAR(50),	--Column 6
	COD_ORDEM_COMPRA	VARCHAR(50),	--Column 7
	NUM_ORDEM_ITEM		VARCHAR(50),	--Column 8
	NUM_DOCTO			VARCHAR(50),	--Column 9
	QTD_PEDIDA			VARCHAR(50),	--Column 10
	QTD_RECEBIDA		VARCHAR(50),	--Column 11
	VLR_PEDIDO			VARCHAR(50),	--Column 12
	VLR_RECEBIDO		VARCHAR(50),	--Column 13
	COD_GRP_MERCADO		VARCHAR(50),	--Column 14
	DES_GRP_MERCADO		VARCHAR(50),	--Column 15
	DTA_EMISSAO			VARCHAR(50)		--Column 16
	);

SELECT * FROM TXT_P2P_MOV_ORDEM_COMPRA

DROP TABLE dbo.STG_P2P_MOV_ORDEM_COMPRA;
CREATE TABLE dbo.STG_P2P_MOV_ORDEM_COMPRA (
	IDE_STAGING				INT IDENTITY,
	SKY_AUDITKEY			INT,
	DTA_CARGA				DATETIME,
	COD_PLANTA				VARCHAR(04),
	DTA_ENTREGA				DATE,
	STA_ORDEM				VARCHAR(50),
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_FORNECEDOR			VARCHAR(10),
	COD_MATERIAL			VARCHAR(20),
	COD_SOLIC_COMPRA		VARCHAR(10),
	COD_ORDEM_COMPRA		VARCHAR(10),
	NUM_ORDEM_ITEM			VARCHAR(06),
	NUM_DOCTO				VARCHAR(10),
	QTD_PEDIDA				NUMERIC(17,3),
	QTD_RECEBIDA			NUMERIC(17,3),
	VLR_PEDIDO				NUMERIC(17,3),
	VLR_RECEBIDO			NUMERIC(17,3),
	DTA_EMISSAO				DATE,
	COD_QUALITY				CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_MOV_ORDEM_COMPRA PRIMARY KEY (IDE_STAGING)
	);

SELECT * FROM STG_P2P_MOV_ORDEM_COMPRA

DROP TABLE dbo.HST_P2P_MOV_ORDEM_COMPRA;
CREATE TABLE dbo.HST_P2P_MOV_ORDEM_COMPRA (
	COD_PLANTA				VARCHAR(04),
	DTA_ENTREGA				DATE,
	STA_ORDEM				VARCHAR(50),
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_FORNECEDOR			VARCHAR(10),
	COD_MATERIAL			VARCHAR(20),
	COD_SOLIC_COMPRA		VARCHAR(10),
	COD_ORDEM_COMPRA		VARCHAR(10),
	NUM_ORDEM_ITEM			VARCHAR(06),
	NUM_DOCTO				VARCHAR(10),
	QTD_PEDIDA				NUMERIC(17,3),
	QTD_RECEBIDA			NUMERIC(17,3),
	VLR_PEDIDO				NUMERIC(17,3),
	VLR_RECEBIDO			NUMERIC(17,3),
	DTA_EMISSAO				DATE
	);

	CREATE INDEX IX_HST_P2P_MOV_ORDEM_COMPRA_01 ON HST_P2P_MOV_ORDEM_COMPRA (COD_PLANTA,DTA_EMISSAO);


DROP TABLE dbo.FAT_P2P_MOV_ORDEM_COMPRA;
CREATE TABLE dbo.FAT_P2P_MOV_ORDEM_COMPRA (
	COD_EMPRESA				VARCHAR(04),	--EMPRESA
	COD_PLANTA				VARCHAR(04),	--PLANTA
	COD_PROFIT_CENTER		VARCHAR(04),	--PROFIT CENTER
	DTA_ENTREGA				DATE,
	STA_ORDEM				VARCHAR(50),
	COD_GRUPO_FORNECEDOR	VARCHAR(03),	--COMPRADOR
	COD_FORNECEDOR			VARCHAR(10),	--FORNECEDOR
	COD_MATERIAL			VARCHAR(20),	--MATERIAL
	COD_SOLIC_COMPRA		VARCHAR(10),	--SOLICITACAO
	COD_ORDEM_COMPRA		VARCHAR(10),	--ORDEM COMPRA
	NUM_ORDEM_ITEM			VARCHAR(06),	--NUM ORDEM ITEM
	NUM_DOCTO				VARCHAR(10),	--DOCTO
	QTD_PEDIDA				NUMERIC(17,3),
	QTD_RECEBIDA			NUMERIC(17,3),
	VLR_PEDIDO				NUMERIC(17,3),
	VLR_RECEBIDO			NUMERIC(17,3),
	DTA_EMISSAO				DATE,
	TIP_ITEM				CHAR(01),		--MATERIAL OU SERVICO
	IDE_FORNECEDOR			BIGINT,
	IDE_MATERIAL			BIGINT,
	IDE_ORDEM_COMPRA		BIGINT,
	IDE_SERVICO				BIGINT
	);

	CREATE INDEX IX_FAT_P2P_MOV_ORDEM_COMPRA_01 ON FAT_P2P_MOV_ORDEM_COMPRA (COD_PLANTA,DTA_EMISSAO);


-- Receber os dados da interface SAP_P2P_MOV_SCOMPRAS.txt
DROP TABLE dbo.TXT_P2P_MOV_SOLIC_COMPRA;
CREATE TABLE dbo.TXT_P2P_MOV_SOLIC_COMPRA (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),	--Column 0
	DTA_SOLICITACAO		VARCHAR(50),	--Column 1
	DTA_APROVACAO		VARCHAR(50),	--Column 2
	COD_GRP_FORNECEDOR	VARCHAR(50),	--Column 3
	COD_FORNECEDOR		VARCHAR(50),	--Column 4
	COD_MATERIAL		VARCHAR(50),	--Column 5
	COD_SOLIC_COMPRA	VARCHAR(50),	--Column 6
	COD_ORDEM_COMPRA	VARCHAR(50),	--Column 7
	NUM_DOCTO			VARCHAR(50),	--Column 8
	QTD_SOLICITADA		VARCHAR(50)		--Column 9
	);


SELECT * FROM TXT_P2P_MOV_SOLIC_COMPRA

DROP TABLE dbo.STG_P2P_MOV_SOLIC_COMPRA;
CREATE TABLE dbo.STG_P2P_MOV_SOLIC_COMPRA (
	IDE_STAGING				INT IDENTITY,
	SKY_AUDITKEY			INT,
	DTA_CARGA				DATETIME,
	COD_PLANTA				VARCHAR(04),
	DTA_SOLICITACAO			DATE,
	DTA_APROVACAO			DATE,
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_FORNECEDOR			VARCHAR(10),
	COD_MATERIAL			VARCHAR(20),
	COD_SOLIC_COMPRA		VARCHAR(10),
	COD_ORDEM_COMPRA		VARCHAR(10),
	NUM_DOCTO				VARCHAR(10),
	QTD_SOLICITADA			NUMERIC(17,3),
	DTA_EMISSAO_ORDEM		DATE DEFAULT '2000-01-01',
	COD_QUALITY				CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_MOV_SOLIC_COMPRA PRIMARY KEY (IDE_STAGING)
	);

SELECT * FROM STG_P2P_MOV_SOLIC_COMPRA

DROP TABLE dbo.HST_P2P_MOV_SOLIC_COMPRA;
CREATE TABLE dbo.HST_P2P_MOV_SOLIC_COMPRA (
	COD_PLANTA				VARCHAR(04),
	DTA_SOLICITACAO			DATE,
	DTA_APROVACAO			DATE,
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_FORNECEDOR			VARCHAR(10),
	COD_MATERIAL			VARCHAR(20),
	COD_SOLIC_COMPRA		VARCHAR(10),
	COD_ORDEM_COMPRA		VARCHAR(10),
	NUM_DOCTO				VARCHAR(10),
	QTD_SOLICITADA			NUMERIC(17,3),
	DTA_EMISSAO_ORDEM		DATE
	);

	CREATE INDEX IX_HST_P2P_MOV_SOLIC_COMPRA_01 ON HST_P2P_MOV_SOLIC_COMPRA (COD_PLANTA,DTA_SOLICITACAO);


DROP TABLE dbo.FAT_P2P_MOV_SOLIC_COMPRA;
CREATE TABLE dbo.FAT_P2P_MOV_SOLIC_COMPRA (
	COD_EMPRESA				VARCHAR(04),	--EMPRESA
	COD_PLANTA				VARCHAR(04),	--PLANTA
	COD_PROFIT_CENTER		VARCHAR(04),	--PROFIT CENTER
	DTA_SOLICITACAO			DATE,
	DTA_APROVACAO			DATE,
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_FORNECEDOR			VARCHAR(10),
	COD_MATERIAL			VARCHAR(20),
	COD_SOLIC_COMPRA		VARCHAR(10),
	COD_ORDEM_COMPRA		VARCHAR(10),
	NUM_DOCTO				VARCHAR(10),
	QTD_SOLICITADA			NUMERIC(17,3),
	DTA_EMISSAO_ORDEM		DATE,
	TIP_ITEM				CHAR(01),		--MATERIAL OU SERVICO
	IDE_FORNECEDOR			BIGINT,
	IDE_MATERIAL			BIGINT,
	IDE_SOLIC_COMPRA		BIGINT,
	IDE_ORDEM_COMPRA		BIGINT,
	IDE_SERVICO				BIGINT
	);

	CREATE INDEX IX_FAT_P2P_MOV_SOLIC_COMPRA_01 ON FAT_P2P_MOV_SOLIC_COMPRA (COD_PLANTA,DTA_SOLICITACAO);


-- Receber os dados da interface SAP_P2P_CAD_NFISCAL.txt
DROP TABLE dbo.TXT_P2P_CAD_NF_ENTRADA;
CREATE TABLE dbo.TXT_P2P_CAD_NF_ENTRADA (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),	--Column 0
	NUM_DOCTO			VARCHAR(50),	--Column 1
	COD_CFOP			VARCHAR(50),	--Column 2
	TIP_NFISCAL			VARCHAR(50),	--Column 3
	DTA_ENTRADA			VARCHAR(50),	--Column 4
	COD_PAGTO			VARCHAR(50),	--Column 5
	COD_NATOP			VARCHAR(250),	--Column 6
	COD_MOEDA			VARCHAR(50),	--Column 7
	DTA_LANCAMENTO		VARCHAR(50),	--Column 8
	TIP_FRETE			VARCHAR(50)		--Column 9
	);

DROP TABLE dbo.STG_P2P_CAD_NF_ENTRADA;
CREATE TABLE dbo.STG_P2P_CAD_NF_ENTRADA (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(04),
	NUM_DOCTO			VARCHAR(10),
	COD_CFOP			VARCHAR(06),
	TIP_NFISCAL			VARCHAR(20),
	DTA_ENTRADA			DATE,
	COD_PAGTO			VARCHAR(50),
	COD_NATOP			VARCHAR(50),
	COD_MOEDA			VARCHAR(03),
	DTA_LANCAMENTO		DATE,
	TIP_FRETE			VARCHAR(50),
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_NF_ENTRADA PRIMARY KEY (IDE_STAGING)
	);


DROP TABLE dbo.DIM_P2P_CAD_NF_ENTRADA;
CREATE TABLE dbo.DIM_P2P_CAD_NF_ENTRADA (
	IDE_NF_ENTRADA		BIGINT IDENTITY,
	COD_PLANTA			VARCHAR(04) NOT NULL,
	NUM_DOCTO			VARCHAR(10) NOT NULL,
	COD_CFOP			VARCHAR(06) NOT NULL,
	TIP_NFISCAL			VARCHAR(20) NOT NULL,
	DTA_ENTRADA			DATE NOT NULL,
	COD_PAGTO			VARCHAR(50),
	COD_NATOP			VARCHAR(50),
	COD_MOEDA			VARCHAR(03),
	DTA_LANCAMENTO		DATE,	--DTA_EMISSAO
	TIP_FRETE			VARCHAR(50),
	CONSTRAINT PK_DIM_P2P_CAD_NF_ENTRADA PRIMARY KEY (COD_PLANTA, NUM_DOCTO, COD_CFOP, TIP_NFISCAL, DTA_ENTRADA, COD_PAGTO)
	);

	INSERT INTO DIM_P2P_CAD_NF_ENTRADA VALUES ('4015','000000000','XXXXXX','COMPRAS','2018-01-01','XXXX SEM INFORMACAO','COMPRA SEM INFORMACAO','BRL','2018-01-01','NDA');
	INSERT INTO DIM_P2P_CAD_NF_ENTRADA VALUES ('4015','000000000','XXXXXX','DEVOLUÇÃO','2018-01-01','XXXX SEM INFORMACAO','COMPRA SEM INFORMACAO','BRL','2018-01-01','NDA');

-- Receber os dados da interface SAP_P2P_CAD_OCOMPRAS.txt
DROP TABLE dbo.TXT_P2P_CAD_ORDEM_COMPRA;
CREATE TABLE dbo.TXT_P2P_CAD_ORDEM_COMPRA (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),	--Column 0
	COD_ORDEM_COMPRA	VARCHAR(50),	--Column 1
	DTA_EMISSAO			VARCHAR(50),	--Column 2
	DES_EMISSOR			VARCHAR(50),	--Column 3
	COD_MOEDA			VARCHAR(50),	--Column 4
	STA_ORDEM			VARCHAR(50)		--Column 5
	);

SELECT * FROM TXT_P2P_CAD_ORDEM_COMPRA

DROP TABLE dbo.STG_P2P_CAD_ORDEM_COMPRA;
CREATE TABLE dbo.STG_P2P_CAD_ORDEM_COMPRA (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(04),
	COD_ORDEM_COMPRA	VARCHAR(10),
	DTA_EMISSAO			DATE,
	DES_EMISSOR			VARCHAR(50),
	COD_MOEDA			VARCHAR(03),
	STA_ORDEM			VARCHAR(50),
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_ORDEM_COMPRA PRIMARY KEY (IDE_STAGING)
	);


DROP TABLE dbo.DIM_P2P_CAD_ORDEM_COMPRA;
CREATE TABLE dbo.DIM_P2P_CAD_ORDEM_COMPRA (
	IDE_ORDEM_COMPRA	BIGINT IDENTITY,
	COD_PLANTA			VARCHAR(04),
	COD_ORDEM_COMPRA	VARCHAR(10),
	DTA_EMISSAO			DATE,
	DES_EMISSOR			VARCHAR(50),
	COD_MOEDA			VARCHAR(03),
	STA_ORDEM			VARCHAR(50),
	CONSTRAINT PK_DIM_P2P_CAD_ORDEM_COMPRA PRIMARY KEY (COD_PLANTA, COD_ORDEM_COMPRA)
	);

	INSERT INTO DIM_P2P_CAD_ORDEM_COMPRA VALUES ('4015','0000000000','2018-01-01','','BRL','NAO INFORMADO');


-- Receber os dados da interface SAP_P2P_CAD_SCOMPRAS.txt
DROP TABLE dbo.TXT_P2P_CAD_SOLIC_COMPRA;
CREATE TABLE dbo.TXT_P2P_CAD_SOLIC_COMPRA (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_PLANTA			VARCHAR(50),	--Column 0
	COD_SOLIC_COMPRA	VARCHAR(50),	--Column 1
	TIP_SOLICITACAO		VARCHAR(50),	--Column 2
	DTA_CRIACAO			VARCHAR(50),	--Column 3
	COD_SOLICITANTE		VARCHAR(50),	--Column 4
	COD_GRP_FORNECEDOR	VARCHAR(50),	--Column 5
	COD_APROVADOR		VARCHAR(50),	--Column 6
	COD_URGENCIA		VARCHAR(50),	--Column 7
	DTA_APROVACAO		VARCHAR(50)		--Column 8
	);


DROP TABLE dbo.STG_P2P_CAD_SOLIC_COMPRA;
CREATE TABLE dbo.STG_P2P_CAD_SOLIC_COMPRA (
	IDE_STAGING				INT IDENTITY,
	SKY_AUDITKEY			INT,
	DTA_CARGA				DATETIME,
	COD_PLANTA				VARCHAR(04),
	COD_SOLIC_COMPRA		VARCHAR(10),
	TIP_SOLICITACAO			VARCHAR(50),
	DTA_CRIACAO				DATE,
	COD_SOLICITANTE			VARCHAR(50),
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_APROVADOR			VARCHAR(50),
	COD_URGENCIA			VARCHAR(50),
	DTA_APROVACAO			DATE,
	COD_QUALITY				CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_SOLIC_COMPRA PRIMARY KEY (IDE_STAGING)
	);


DROP TABLE dbo.DIM_P2P_CAD_SOLIC_COMPRA;
CREATE TABLE dbo.DIM_P2P_CAD_SOLIC_COMPRA (
	IDE_SOLIC_COMPRA		BIGINT IDENTITY,
	COD_PLANTA				VARCHAR(04),
	COD_SOLIC_COMPRA		VARCHAR(10),
	TIP_SOLICITACAO			VARCHAR(50),
	DTA_CRIACAO				DATE,
	COD_SOLICITANTE			VARCHAR(50),
	COD_GRUPO_FORNECEDOR	VARCHAR(03),
	COD_APROVADOR			VARCHAR(50),
	COD_URGENCIA			VARCHAR(50),
	DTA_APROVACAO			DATE,
	CONSTRAINT PK_DIM_P2P_CAD_SOLIC_COMPRA PRIMARY KEY (COD_PLANTA,COD_SOLIC_COMPRA)
	);

	INSERT INTO DIM_P2P_CAD_SOLIC_COMPRA VALUES ('4015','0000000000','X NAO INFORMADO','2018-01-01','NAO INFORMADO','000','NAO INFORMADO','NAO INFORMADO','2018-01-01')


--///// AVALICAÇÃO DE FORNECEDORES /////--

--///// Arquivo :: SAP_P2P_MOV_AV_FORN
DROP TABLE dbo.TXT_P2P_AVF_FORNECIMENTO;
CREATE TABLE dbo.TXT_P2P_AVF_FORNECIMENTO (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	DTA_PERIODO			VARCHAR(50),	--Periodo
	COD_ORG_C			VARCHAR(50),	--Org C
	COD_FORNECEDOR		VARCHAR(50),	--Fornecedor
	COD_MATERIAL		VARCHAR(50),	--Material
	COD_PLANTA			VARCHAR(50),	--Planta
	QTD_PO				VARCHAR(50),	--Qtd PO
	QTD_REC				VARCHAR(50),	--Qtd Rec
	DTA_PREVISTA		VARCHAR(50),	--Data Prevista
	DTA_RECEBIDA		VARCHAR(50)		--Data Recebida
	);

--///// Arquivo :: SAP_P2P_MOV_AV_FORN_MATERIAIS
DROP TABLE dbo.TXT_P2P_AVF_MATERIAL;
CREATE TABLE dbo.TXT_P2P_AVF_MATERIAL (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	DTA_PERIODO			VARCHAR(50),	--Periodo
	COD_ORG_C			VARCHAR(50),	--Org C
	COD_FORNECEDOR		VARCHAR(50),	--Fornecedor
	COD_CRITERIO		VARCHAR(50),	--Criterio
	VLR_NOTA			VARCHAR(50),	--Nota
	COD_USUARIO			VARCHAR(50),	--Usuario
	DTA_CRIACAO			VARCHAR(50),	--Data Criacao
	VLR_NOTA1			VARCHAR(50),	--Valor Nota1
	VLR_NOTA5			VARCHAR(50)		--Valor Nota5
	);

--///// Arquivo :: SAP_P2P_MOV_AV_FORN_NOTA_GLOBAL
DROP TABLE dbo.TXT_P2P_AVF_NOTA_GLOBAL;
CREATE TABLE dbo.TXT_P2P_AVF_NOTA_GLOBAL (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_ORG_C			VARCHAR(50),	--Org C
	COD_FORNECEDOR		VARCHAR(50),	--Fornecedor
	CHV_POND			VARCHAR(50),	--Chv Pond
	VLR_NOTA_GLOBAL		VARCHAR(50),	--Nota Global
	COD_USUARIO			VARCHAR(50),	--Usuario
	DTA_CRIACAO			VARCHAR(50)		--Data Criacao
	);

--///// Arquivo :: SAP_P2P_MOV_AV_FORN_RECEBIMENTO
DROP TABLE dbo.TXT_P2P_AVF_RECEBIMENTO;
CREATE TABLE dbo.TXT_P2P_AVF_RECEBIMENTO (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	DTA_PERIODO			VARCHAR(50),	--Periodo
	NUM_LOTE_CONTROLE	VARCHAR(50),	--Lote Controle
	COD_ORG_C			VARCHAR(50),	--Org C
	COD_FORNECEDOR		VARCHAR(50),	--Fornecedor
	COD_MATERIAL		VARCHAR(50),	--Material
	COD_PLANTA			VARCHAR(50),	--Planta
	QTD_RECEBIDA		VARCHAR(50),	--Qtde
	COD_USUARIO			VARCHAR(50),	--Usuario
	DTA_CRIACAO			VARCHAR(50),	--Data Criacao
	COD_STATUS			VARCHAR(50)		--Status
	);

--DROP TABLE dbo.STG_P2P_AVF_RECEBIMENTO;
CREATE TABLE dbo.STG_P2P_AVF_RECEBIMENTO (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	DTA_PERIODO			VARCHAR(07),
	NUM_LOTE_CONTROLE	VARCHAR(30),
	COD_ORG_C			VARCHAR(10),	--Org C
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	COD_MATERIAL		VARCHAR(20),	--Material
	COD_PLANTA			VARCHAR(04),	--Planta
	QTD_RECEBIDA		NUMERIC(17,3),	--Qtd Recebida
	COD_USUARIO			VARCHAR(10),	--Usuario
	DTA_CRIACAO			DATE,			--Data Criacao
	COD_STATUS			VARCHAR(05),	--Cod Status
	DES_STATUS			VARCHAR(20),	--Des Status
	COD_QUALITY			CHAR(01) DEFAULT 'S'
	);


--DROP TABLE dbo.HST_P2P_AVF_RECEBIMENTO;
CREATE TABLE dbo.HST_P2P_AVF_RECEBIMENTO (
	DTA_PERIODO			VARCHAR(07),
	NUM_LOTE_CONTROLE	VARCHAR(30),
	COD_ORG_C			VARCHAR(10),	--Org C
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	COD_MATERIAL		VARCHAR(20),	--Material
	COD_PLANTA			VARCHAR(04),	--Planta
	QTD_RECEBIDA		NUMERIC(17,3),	--Qtd Recebida
	COD_USUARIO			VARCHAR(10),	--Usuario
	DTA_CRIACAO			DATE,			--Data Criacao
	COD_STATUS			VARCHAR(05),	--Cod Status
	DES_STATUS			VARCHAR(20),	--Des Status
	CONSTRAINT PK_HST_P2P_AVF_RECEBIMENTO PRIMARY KEY NONCLUSTERED (COD_PLANTA, DTA_PERIODO, NUM_LOTE_CONTROLE, COD_FORNECEDOR)
	);

--DROP TABLE dbo.REL_P2P_AVF_ITEM;
CREATE TABLE dbo.REL_P2P_AVF_ITEM (
	DTA_ANO				INT,
	COD_ORG_C			VARCHAR(10),
	COD_PLANTA			VARCHAR(04),
	COD_FORNECEDOR		VARCHAR(10),
	DES_FORNECEDOR		VARCHAR(50),
	COD_MATERIAL		VARCHAR(20),
	DES_MATERIAL		VARCHAR(100),
	COD_AVALIACAO		INT,
	DES_AVALIACAO		VARCHAR(20),
	JAN_IN				NUMERIC(17,3),
	JAN_MD				NUMERIC(17,3),
	JAN_OUT				NUMERIC(17,3),
	FEV_IN				NUMERIC(17,3),
	FEV_MD				NUMERIC(17,3),
	FEV_OUT				NUMERIC(17,3),
	MAR_IN				NUMERIC(17,3),
	MAR_MD				NUMERIC(17,3),
	MAR_OUT				NUMERIC(17,3),
	ABR_IN				NUMERIC(17,3),
	ABR_MD				NUMERIC(17,3),
	ABR_OUT				NUMERIC(17,3),
	MAI_IN				NUMERIC(17,3),
	MAI_MD				NUMERIC(17,3),
	MAI_OUT				NUMERIC(17,3),
	JUN_IN				NUMERIC(17,3),
	JUN_MD				NUMERIC(17,3),
	JUN_OUT				NUMERIC(17,3),
	JUL_IN				NUMERIC(17,3),
	JUL_MD				NUMERIC(17,3),
	JUL_OUT				NUMERIC(17,3),
	AGO_IN				NUMERIC(17,3),
	AGO_MD				NUMERIC(17,3),
	AGO_OUT				NUMERIC(17,3),
	SET_IN				NUMERIC(17,3),
	SET_MD				NUMERIC(17,3),
	SET_OUT				NUMERIC(17,3),
	OUT_IN				NUMERIC(17,3),
	OUT_MD				NUMERIC(17,3),
	OUT_OUT				NUMERIC(17,3),
	NOV_IN				NUMERIC(17,3),
	NOV_MD				NUMERIC(17,3),
	NOV_OUT				NUMERIC(17,3),
	DEZ_IN				NUMERIC(17,3),
	DEZ_MD				NUMERIC(17,3),
	DEZ_OUT				NUMERIC(17,3)
	);




--///// Arquivo :: SAP_P2P_MOV_AV_FORN_SERVICOS
DROP TABLE dbo.TXT_P2P_AVF_SERVICO;
CREATE TABLE dbo.TXT_P2P_AVF_SERVICO (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_ORG_C			VARCHAR(50),	--Org C
	COD_FORNECEDOR		VARCHAR(50),	--Fornecedor
	COD_CRITERIO		VARCHAR(50),	--Criterio
	VLR_NOTA			VARCHAR(50),	--Nota
	COD_USUARIO			VARCHAR(50),	--Usuario
	DTA_CRIACAO			VARCHAR(50),	--Data Criacao
	VLR_NOTA1			VARCHAR(50),	--Valor Nota1
	VLR_NOTA2			VARCHAR(50),	--Valor Nota2
	VLR_NOTA3			VARCHAR(50),	--Valor Nota3
	VLR_NOTA4			VARCHAR(50),	--Valor Nota4
	VLR_NOTA5			VARCHAR(50),	--Valor Nota5
	VLR_NOTA6			VARCHAR(50),	--Valor Nota6
	VLR_NOTA7			VARCHAR(50),	--Valor Nota7
	VLR_NOTA8			VARCHAR(50),	--Valor Nota8
	VLR_NOTA9			VARCHAR(50),	--Valor Nota9
	VLR_NOTA10			VARCHAR(50)		--Valor Nota10
	);

--///// Arquivo :: SAP_P2P_MOV_AV_FORN_CONSUMO
DROP TABLE dbo.TXT_P2P_AVF_CONSUMO;
CREATE TABLE dbo.TXT_P2P_AVF_CONSUMO (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	TIP_MOVIMENTO		VARCHAR(50),	--Tp.Mov		[MSEG :: BWART]
	COD_MATERIAL		VARCHAR(50),	--Material		[MSEG :: MATNR]
	COD_PLANTA			VARCHAR(50),	--Planta		[MSEG :: WERKS]
	NUM_LOTE			VARCHAR(50),	--Lote			[MSEG :: CHARG]
	COD_FORNECEDOR		VARCHAR(50),	--Fornecedor	[MCH1 :: LIFNR]
	DTA_CONSUMO			VARCHAR(50),	--Data			[MSEG :: CPUDT_MKPF]
	QTD_CONSUMO			VARCHAR(50)		--Qtde			[MSEG :: MENGE]
	);


--DROP TABLE dbo.STG_P2P_AVF_CONSUMO;
CREATE TABLE dbo.STG_P2P_AVF_CONSUMO (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	DTA_PERIODO			VARCHAR(07),
	COD_ORG_C			VARCHAR(10),	--Org C
	TIP_MOVIMENTO		INT,
	COD_MATERIAL		VARCHAR(20),	--Material
	COD_PLANTA			VARCHAR(04),	--Planta
	NUM_LOTE_CONTROLE	VARCHAR(30),
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	DTA_CONSUMO			DATE,			--Data Consumo
	QTD_CONSUMO			NUMERIC(17,3),	--Qtd Consumo
	COD_QUALITY			CHAR(01) DEFAULT 'S'
	);

--DROP TABLE dbo.HST_P2P_AVF_CONSUMO;
CREATE TABLE dbo.HST_P2P_AVF_CONSUMO (
	DTA_PERIODO			VARCHAR(07),
	COD_ORG_C			VARCHAR(10),	--Org C
	TIP_MOVIMENTO		INT,
	COD_MATERIAL		VARCHAR(20),	--Material
	COD_PLANTA			VARCHAR(04),	--Planta
	NUM_LOTE_CONTROLE	VARCHAR(30),
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	DTA_CONSUMO			DATE,			--Data Consumo
	QTD_CONSUMO			NUMERIC(17,3),	--Qtd Consumo
	CONSTRAINT PK_HST_P2P_AVF_CONSUMO PRIMARY KEY NONCLUSTERED (COD_PLANTA, DTA_CONSUMO, NUM_LOTE_CONTROLE, COD_FORNECEDOR, COD_MATERIAL)
	);


--///// TABELA SE-SUITE RNC
DROP TABLE dbo.TMP_P2P_AVF_RNC_CAPA;
CREATE TABLE dbo.TMP_P2P_AVF_RNC_CAPA (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	NRSEQNC				NUMERIC(12),
	NRRNC				VARCHAR(16),
	CDCLASSIF			NUMERIC(12),
	SGCLASSIF			VARCHAR(10),
	NMCLASSIF			VARCHAR(50),
	CDMETODO			NUMERIC(12),
	SGMETODO			VARCHAR(20),
	NMMETODO			VARCHAR(100),
	CDEQUIPE			NUMERIC(12),
	SGEQUIPE			VARCHAR(20),
	NMEQUIPE			VARCHAR(100),
	CDUSUALIDER			NUMERIC(12),
	NMRNC				VARCHAR(255),
	DTNC				DATETIME,
	CDAREANC			NUMERIC(12),
	CDSITUACAO			NUMERIC(12),
	CDSITESTADO			NUMERIC(12),
	CDAREAEMIT			NUMERIC(12),
	DTEMISSAO			DATETIME,
	DSRNC				TEXT,
	IDPERMES			VARCHAR(07),
	IDPERANO			VARCHAR(04),
	DTCREATERNC			DATETIME,
	DTENCERRADO			DATETIME,
	IDFASEENC			NUMERIC(12),
	IDVERSAORNC			NUMERIC(12)
	);

--///// TABELA SE-SUITE RNC
DROP TABLE dbo.TMP_P2P_AVF_RNC_ITEM;
CREATE TABLE dbo.TMP_P2P_AVF_RNC_ITEM (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	CDOCURRENCE			NUMERIC(12),
	CDCLASSIF			NUMERIC(12),
	NM_CAMPO			VARCHAR(30),
	CAMPO				VARCHAR(255),
	LABEL				VARCHAR(255),
	CDATTRIBUTE			NUMERIC(12),
	CDVALUE				NUMERIC(12),
	VALOR				VARCHAR(30)
	);

--///// TABELA SE-SUITE RNC
DROP TABLE dbo.TMP_P2P_AVF_RNC_ITEM_PVT;
CREATE TABLE dbo.TMP_P2P_AVF_RNC_ITEM_PVT (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	CDOCURRENCE			NUMERIC(12),
	CDCLASSIF			NUMERIC(12),
	DES_DESVIO1			VARCHAR(30),
	DES_CLASSIF_RNC		VARCHAR(30),
	DES_OPERACAO		VARCHAR(30),
	DES_MAQUINA			VARCHAR(30),
	COD_TIPO_NOTA		VARCHAR(30),
	QTD_QUILO			VARCHAR(30),
	DES_TIPO_MP			VARCHAR(30),
	COD_PRODUTO			VARCHAR(30),
	DES_FORNECEDOR		VARCHAR(30),
	COD_FORNECEDOR		VARCHAR(30),
	DES_PRODUTO			VARCHAR(30),
	GRP_MATERIAL		VARCHAR(30),
	COD_PLANTA			VARCHAR(30)
	);

--///// Arquivo :: AV Dados de MP para Avaliação de Fornecedor.XLSX
DROP TABLE dbo.TXT_P2P_AVF_RNC;
CREATE TABLE dbo.TXT_P2P_AVF_RNC (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	NUM_RNC				VARCHAR(50),	--Nr. ocor.
	DTA_ANO				VARCHAR(50),	--Ano - Ocorrência
	DTA_MES				VARCHAR(50),	--Mês - Ocorrência
	COD_PRODUTO			VARCHAR(50),	--MAU MAT_FOR_CODPROD
	DES_PRODUTO			VARCHAR(50),	--MAU MAT_FOR_DESCPROD
	COD_FORNECEDOR		VARCHAR(50),	--SAP MAU MAT_FOR_VENDOR
	DES_FORNECEDOR		VARCHAR(50),	--MAU MAT_FOR_DESCFORN
	DES_DESVIO			VARCHAR(50),	--MAU DESVIO 1:
	DES_CLASSIF			VARCHAR(50),	--MAU CLASSIF. RNC
	TIP_ACAO			VARCHAR(50),	--Tipo da ação
	DES_ACAO			VARCHAR(250),	--Ação
	DES_OCORRENCIA		VARCHAR(250),	--Ocorrência
	QTD_QUILO			VARCHAR(50)		--MAU QTDE.
	);

--DROP TABLE dbo.STG_P2P_AVF_RNC;
CREATE TABLE dbo.STG_P2P_AVF_RNC (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	NUM_RNC				INT,			--Nr. ocor.
	DTA_PERIODO			VARCHAR(07),	--Dta Periodo
	DTA_RNC				DATE,
	COD_PLANTA			VARCHAR(04),
	COD_MATERIAL		VARCHAR(20),	--MAU MAT_FOR_CODPROD
	COD_FORNECEDOR		VARCHAR(10),	--SAP MAU MAT_FOR_VENDOR
	COD_DESVIO			VARCHAR(04),	--COD DESVIO
	DES_DESVIO			VARCHAR(50),	--MAU DESVIO 1:
	COD_CLASSIF			VARCHAR(04),	--COD CLASSIF
	DES_CLASSIF			VARCHAR(50),	--MAU CLASSIF. RNC
	TIP_ACAO			VARCHAR(50),	--Tipo da ação
	DES_ACAO			VARCHAR(250),	--Ação
	DES_OCORRENCIA		VARCHAR(250),	--Ocorrência
	QTD_QUILO			NUMERIC(17,3),	--MAU QTDE.
	COD_QUALITY			CHAR(01) DEFAULT 'S'
	);

--DROP TABLE dbo.HST_P2P_AVF_RNC;
CREATE TABLE dbo.HST_P2P_AVF_RNC (
	NUM_RNC				INT,			--Nr. ocor.
	DTA_PERIODO			VARCHAR(07),	--Dta Periodo
	DTA_RNC				DATE,
	COD_PLANTA			VARCHAR(04),
	COD_MATERIAL		VARCHAR(20),	--MAU MAT_FOR_CODPROD
	COD_FORNECEDOR		VARCHAR(10),	--SAP MAU MAT_FOR_VENDOR
	COD_DESVIO			VARCHAR(04),	--COD DESVIO
	DES_DESVIO			VARCHAR(50),	--MAU DESVIO 1:
	COD_CLASSIF			VARCHAR(04),	--COD CLASSIF
	DES_CLASSIF			VARCHAR(50),	--MAU CLASSIF. RNC
	TIP_ACAO			VARCHAR(50),	--Tipo da ação
	DES_ACAO			VARCHAR(250),	--Ação
	DES_OCORRENCIA		VARCHAR(250),	--Ocorrência
	QTD_QUILO			NUMERIC(17,3),	--MAU QTDE.
	CONSTRAINT PK_HST_P2P_AVF_RNC PRIMARY KEY NONCLUSTERED (COD_PLANTA, NUM_RNC)
	);


--///// Arquivo :: SAP_P2P_MOV_AV_FORN_SERVICOS
--DROP TABLE dbo.TMP_P2P_AVF_SERVICO;
CREATE TABLE dbo.TMP_P2P_AVF_SERVICO (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_ORG_C			VARCHAR(10),	--Org C
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	COD_CRITERIO		VARCHAR(02),	--Criterio
	VLR_NOTA			NUMERIC(17,3),	--Nota
	COD_USUARIO			VARCHAR(20),	--Usuario
	DTA_CRIACAO			DATE,			--Data Criacao
	VLR_NOTA1			NUMERIC(17,3),	--Valor Nota1
	VLR_NOTA2			NUMERIC(17,3),	--Valor Nota2
	VLR_NOTA3			NUMERIC(17,3),	--Valor Nota3
	VLR_NOTA4			NUMERIC(17,3),	--Valor Nota4
	VLR_NOTA5			NUMERIC(17,3),	--Valor Nota5
	VLR_NOTA6			NUMERIC(17,3),	--Valor Nota6
	VLR_NOTA7			NUMERIC(17,3),	--Valor Nota7
	VLR_NOTA8			NUMERIC(17,3),	--Valor Nota8
	VLR_NOTA9			NUMERIC(17,3),	--Valor Nota9
	VLR_NOTA10			NUMERIC(17,3),	--Valor Nota10
	COD_QUALITY			CHAR(01) DEFAULT 'S'
	);


--DROP TABLE dbo.HST_P2P_AVF_SERVICO;
CREATE TABLE dbo.HST_P2P_AVF_SERVICO (
	COD_ORG_C			VARCHAR(10),	--Org C
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	COD_CRITERIO		VARCHAR(02),	--Criterio
	VLR_NOTA			NUMERIC(17,3),	--Nota
	COD_USUARIO			VARCHAR(20),	--Usuario
	DTA_CRIACAO			DATE,			--Data Criacao
	DTA_BASE			DATE,			--Data Base para replicaçao
	VLR_NOTA1			NUMERIC(17,3),	--Valor Nota1
	VLR_NOTA2			NUMERIC(17,3),	--Valor Nota2
	VLR_NOTA3			NUMERIC(17,3),	--Valor Nota3
	VLR_NOTA4			NUMERIC(17,3),	--Valor Nota4
	VLR_NOTA5			NUMERIC(17,3),	--Valor Nota5
	VLR_NOTA6			NUMERIC(17,3),	--Valor Nota6
	VLR_NOTA7			NUMERIC(17,3),	--Valor Nota7
	VLR_NOTA8			NUMERIC(17,3),	--Valor Nota8
	VLR_NOTA9			NUMERIC(17,3),	--Valor Nota9
	VLR_NOTA10			NUMERIC(17,3)	--Valor Nota10
	);


--DROP TABLE dbo.HST_P2P_AVF_SERVICO_UPVT;
CREATE TABLE dbo.HST_P2P_AVF_SERVICO_UPVT (
	COD_ORG_C			VARCHAR(10),	--Org C
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	COD_CRITERIO		VARCHAR(02),	--Criterio
	VLR_NOTA			NUMERIC(17,3),	--Nota
	COD_USUARIO			VARCHAR(20),	--Usuario
	DTA_CRIACAO			DATE,			--Data Criacao
	ORD_NOTAS			VARCHAR(50),
	VLR_NOTAS			NUMERIC(17,3),	--Valor Nota1
	);


--DROP TABLE dbo.REL_P2P_AVF_SERVICO;
CREATE TABLE dbo.REL_P2P_AVF_SERVICO (
	COD_ORG_C			VARCHAR(10),	--Org C
	COD_FORNECEDOR		VARCHAR(10),	--Fornecedor
	DES_FORNECEDOR		VARCHAR(50),
	DTA_ANO				INT,
	DTA_MES				INT,
	DTA_PERIODO			VARCHAR(07),
	COD_CRITERIO		VARCHAR(02),	--Criterio
	VLR_SCORE			NUMERIC(17,3),
	VLR_PESO			NUMERIC(17,3),
	VLR_PARC_GLOBAL		NUMERIC(17,3)
	);

TRUNCATE TABLE dbo.REL_P2P_AVF_SERVICO;


--///// Arquivo :: SAP_P2P_CAD_SERVICOS
DROP TABLE dbo.TXT_P2P_CAD_SERVICO;
CREATE TABLE dbo.TXT_P2P_CAD_SERVICO (
	IDE_TEMP			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_SERVICO			VARCHAR(250),	--Column 0
	DES_SERVICO			VARCHAR(250),	--Column 1
	COD_GRP_MERCADO		VARCHAR(250),	--Column 3
	COD_UND_BASC		VARCHAR(250),	--Column 4
	DES_NV1_HIERARQUIA	VARCHAR(250),	--Column 3
	DES_NV2_HIERARQUIA	VARCHAR(250),	--Column 8
	COD_CONTROLE		VARCHAR(250)	--Column 9
	);

DROP TABLE dbo.STG_P2P_CAD_SERVICO;
CREATE TABLE dbo.STG_P2P_CAD_SERVICO (
	IDE_STAGING			INT IDENTITY,
	SKY_AUDITKEY		INT,
	DTA_CARGA			DATETIME,
	COD_SERVICO			VARCHAR(20),	--Column 0
	DES_SERVICO			VARCHAR(100),	--Column 1
	COD_GRP_MERCADO		VARCHAR(50),	--Column 3
	COD_UND_BASC		VARCHAR(05),	--Column 4
	DES_NV1_HIERARQUIA	VARCHAR(50),	--Column 3
	DES_NV2_HIERARQUIA	VARCHAR(50),	--Column 8
	COD_CONTROLE		VARCHAR(20),	--Column 9
	COD_QUALITY			CHAR(01) DEFAULT 'S',
	CONSTRAINT PK_STG_P2P_CAD_SERVICO PRIMARY KEY (IDE_STAGING)
	);

DROP TABLE dbo.DIM_P2P_CAD_SERVICO;
CREATE TABLE dbo.DIM_P2P_CAD_SERVICO (
	IDE_SERVICO			BIGINT IDENTITY,
	COD_SERVICO			VARCHAR(20),	--Column 0
	DES_SERVICO			VARCHAR(100),	--Column 1
	COD_GRP_MERCADO		VARCHAR(50),	--Column 3
	COD_UND_BASC		VARCHAR(05),	--Column 4
	DES_NV1_HIERARQUIA	VARCHAR(50),	--Column 3
	DES_NV2_HIERARQUIA	VARCHAR(50),	--Column 8
	COD_CONTROLE		VARCHAR(20),	--Column 9
	CONSTRAINT PK_DIM_P2P_CAD_SERVICO PRIMARY KEY (COD_SERVICO)
	);

--////////////////////////////////////////////////////////// DE PARA SISTEMA LEGADO PARA ESTOQUE /////////////////////////////////////////////

DROP TABLE dbo.TMP_P2P_PRODUTO_X_CLIENTE_LEGADO;
CREATE TABLE dbo.TMP_P2P_PRODUTO_X_CLIENTE_LEGADO (
	IDE_TEMP			INT IDENTITY,
	COD_PLANTA			VARCHAR(04),
	COD_PRODUTO_BAAN	VARCHAR(07),
	COD_CLIENTE_BAAN	VARCHAR(06)
	);

DROP TABLE dbo.CAD_P2P_PRODUTO_X_CLIENTE_LEGADO;
CREATE TABLE dbo.CAD_P2P_PRODUTO_X_CLIENTE_LEGADO (
	IDE_CADASTRO		BIGINT IDENTITY,
	COD_PLANTA			VARCHAR(04),
	COD_PRODUTO_BAAN	VARCHAR(07),
	COD_CLIENTE_BAAN	VARCHAR(06),
	COD_MATERIAL		VARCHAR(20),	--Material Code
	COD_PARCEIRO		VARCHAR(15),	--Customer/Vendor
	CLI_CNPJ			VARCHAR(20)
	);

	CREATE INDEX IX_CAD_P2P_PRODUTO_X_CLIENTE_LEGADO ON CAD_P2P_PRODUTO_X_CLIENTE_LEGADO (COD_PLANTA, COD_MATERIAL, COD_PARCEIRO);

DROP TABLE dbo.CAD_P2P_MATERIAL_X_PARCEIRO;
CREATE TABLE dbo.CAD_P2P_MATERIAL_X_PARCEIRO (
	IDE_CADASTRO		BIGINT IDENTITY,
	COD_PLANTA			VARCHAR(04),
	COD_MATERIAL		VARCHAR(20),	--Material Code
	COD_PARCEIRO		VARCHAR(15)		--Customer/Vendor
	);

CREATE INDEX IX_CAD_P2P_MATERIAL_X_PARCEIRO_01 ON CAD_P2P_MATERIAL_X_PARCEIRO (COD_PLANTA, COD_MATERIAL);